package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// Geometric Balance - Light Palette Tokens
val GeoBgLight = Color(0xFFFEF7FF)
val GeoSurfaceLight = Color(0xFFFEF7FF)
val GeoSurfaceVariantLight = Color(0xFFE7E0EC)
val GeoPrimaryLight = Color(0xFF6750A4)
val GeoOnPrimaryLight = Color(0xFFFFFFFF)
val GeoPrimaryContainerLight = Color(0xFFEADDFF)
val GeoOnPrimaryContainerLight = Color(0xFF21005D)
val GeoSecondaryLight = Color(0xFF625B71)
val GeoOnSecondaryLight = Color(0xFFFFFFFF)
val GeoSecondaryContainerLight = Color(0xFFE8DEF8)
val GeoOnSecondaryContainerLight = Color(0xFF1D192B)
val GeoTertiaryLight = Color(0xFF7D5260)
val GeoOnTertiaryLight = Color(0xFFFFFFFF)
val GeoTertiaryContainerLight = Color(0xFFFFD8E4)
val GeoOnTertiaryContainerLight = Color(0xFF31111D)
val GeoOutlineLight = Color(0xFF79747E)
val GeoOutlineVariantLight = Color(0xFFCAC4D0)
val GeoTextPrimaryLight = Color(0xFF1D1B20)
val GeoTextSecondaryLight = Color(0xFF49454F)

// Geometric Balance - Dark Palette Tokens
val GeoBgDark = Color(0xFF141218)
val GeoSurfaceDark = Color(0xFF141218)
val GeoSurfaceVariantDark = Color(0xFF49454F)
val GeoPrimaryDark = Color(0xFFD0BCFF)
val GeoOnPrimaryDark = Color(0xFF381E72)
val GeoPrimaryContainerDark = Color(0xFF4F378B)
val GeoOnPrimaryContainerDark = Color(0xFFEADDFF)
val GeoSecondaryDark = Color(0xFFCCC2DC)
val GeoOnSecondaryDark = Color(0xFF332D41)
val GeoSecondaryContainerDark = Color(0xFF4A4458)
val GeoOnSecondaryContainerDark = Color(0xFFE8DEF8)
val GeoTertiaryDark = Color(0xFFEFB8C8)
val GeoOnTertiaryDark = Color(0xFF492532)
val GeoTertiaryContainerDark = Color(0xFF633B48)
val GeoOnTertiaryContainerDark = Color(0xFFFFD8E4)
val GeoOutlineDark = Color(0xFF938F99)
val GeoOutlineVariantDark = Color(0xFF49454F)
val GeoTextPrimaryDark = Color(0xFFE6E0E9)
val GeoTextSecondaryDark = Color(0xFFCAC4D0)

// Semantic Accents
val GeoSuccessLight = Color(0xFF2E6C38)
val GeoSuccessDark = Color(0xFF8CD693)
val GeoWarningLight = Color(0xFF8F4C00)
val GeoWarningDark = Color(0xFFFFB786)
val GeoDangerLight = Color(0xFFB3261E)
val GeoDangerDark = Color(0xFFF2B8B5)
val GeoInfoLight = Color(0xFF00677F)
val GeoInfoDark = Color(0xFF5CD4F5)
